# Generated by Django 5.2.3 on 2025-06-19 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_type", models.CharField(max_length=50)),
                ("food", models.CharField(max_length=200)),
                ("quantity", models.CharField(max_length=50)),
                ("calories", models.FloatField()),
                ("protein", models.FloatField()),
                ("fat", models.FloatField()),
                ("carbs", models.FloatField()),
                ("fiber", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
