# Generated by Django 5.2.3 on 2025-06-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nu", "0002_meallog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meallog",
            name="food",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="meallog",
            name="meal_type",
            field=models.CharField(max_length=5000),
        ),
    ]
