# Generated by Django 5.2.3 on 2025-06-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nu", "0003_alter_meallog_food_alter_meallog_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="carbs",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fiber",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="protein",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tdee",
            field=models.FloatField(default=0),
        ),
    ]
