# Generated by Django 5.2.3 on 2025-06-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nu", "0004_userprofile_carbs_userprofile_fat_userprofile_fiber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="carbs",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="fat",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="fiber",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="protein",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="tdee",
        ),
    ]
