# Generated by Django 5.2.3 on 2025-06-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nu", "0006_dailysummary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailySummary",
        ),
    ]
