# Generated by Django 5.2.3 on 2025-06-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nu", "0009_delete_dailysummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="calorie_split",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_targets",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
